In [1]:
import numpy as np
import scipy.stats as stats

In [2]:
# 1. Bayesian Inference
def bayesian_inference(prior_B, prob_A_given_B, prob_A):
    """
    Perform Bayesian inference.
    P(B|A) = (P(A|B) * P(B)) / P(A)
    """
    posterior_B_given_A = (prob_A_given_B * prior_B) / prob_A
    return posterior_B_given_A

In [3]:
# 2. Eigen Decomposition
def compute_eigen(matrix):
    values, vectors = np.linalg.eig(matrix)
    return values, vectors

In [4]:
# 3. Determinant and Inverse of a 4x4 Matrix
def calculate_determinant(matrix):
    """
    Compute the determinant of a 4x4 matrix.
    """
    det = np.linalg.det(matrix)
    return det

In [5]:
def calculate_inverse(matrix):
    """
    Compute the inverse of a 4x4 matrix if it exists.
    """
    det = calculate_determinant(matrix)
    if det == 0:
        return None  # The matrix is singular and cannot be inverted.
    inverse = np.linalg.inv(matrix)
    return inverse

In [6]:
# 4. Normal Distribution Characteristics
def describe_normal_distribution():
    """
    Outline characteristics of the Normal distribution.
    """
    characteristics = {
        "Mean (μ)": "Central point of the distribution.",
        "Standard Deviation (σ)": "Indicator of distribution spread.",
        "Symmetry": "Distribution is symmetric about the mean.",
        "68-95-99.7 Rule": "Describes the percentage of data within 1σ, 2σ, and 3σ of the mean."
    }
    return characteristics

In [7]:
def calculate_probability(mean, std_dev, value):
    """
    Compute the probability of a value within a normal distribution.
    """
    probability = stats.norm.cdf(value, loc=mean, scale=std_dev)
    return probability

In [8]:
# Bayesian Inference
prior_B = 0.03  # Prior probability of event B
prob_A_given_B = 0.75  # Probability of event A given B
prob_A = 0.15  # Probability of event A
posterior = bayesian_inference(prior_B, prob_A_given_B, prob_A)
print(f"Posterior Probability: {posterior:.4f}")

Posterior Probability: 0.1500


In [9]:
# Eigen Decomposition
matrix = np.array([[2, 0, 1, 3], [0, 2, 3, 1], [1, 3, 2, 0], [3, 1, 0, 2]])
values, vectors = compute_eigen(matrix)
print(f"Eigenvalues: {values}")
print(f"Eigenvectors: {vectors}")

Eigenvalues: [ 6.00000000e+00  4.00000000e+00 -2.00000000e+00 -5.33636906e-16]
Eigenvectors: [[-0.5 -0.5 -0.5 -0.5]
 [-0.5  0.5 -0.5  0.5]
 [-0.5  0.5  0.5 -0.5]
 [-0.5 -0.5  0.5  0.5]]


In [10]:
# Determinant and Inverse of a 4x4 Matrix
det = calculate_determinant(matrix)
inverse = calculate_inverse(matrix)
print(f"Determinant: {det:.4f}")
if inverse is not None:
    print(f"Inverse: \n{inverse}")
else:
    print("The matrix is singular and cannot be inverted.")

Determinant: 0.0000
The matrix is singular and cannot be inverted.


In [11]:
# Normal Distribution Characteristics and Probabilities
characteristics = describe_normal_distribution()
print("Normal Distribution Characteristics:")
for key, value in characteristics.items():
    print(f"{key}: {value}")

mean = 10
std_dev = 3
value = 14
probability = calculate_probability(mean, std_dev, value)
print(f"Probability of {value} in N({mean}, {std_dev}^2): {probability:.4f}")

Normal Distribution Characteristics:
Mean (μ): Central point of the distribution.
Standard Deviation (σ): Indicator of distribution spread.
Symmetry: Distribution is symmetric about the mean.
68-95-99.7 Rule: Describes the percentage of data within 1σ, 2σ, and 3σ of the mean.
Probability of 14 in N(10, 3^2): 0.9088
